# Generated by Django 2.1.4 on 2019-01-31 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billingname', models.CharField(blank=True, max_length=40, null=True)),
                ('addressline', models.CharField(blank=True, max_length=400, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=400, null=True)),
                ('homeno', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('gstin', models.CharField(blank=True, max_length=25, null=True)),
                ('pan', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('verificationstatus', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryStatus', models.IntegerField(default=0)),
                ('completeDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('material', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10)),
                ('isIgst', models.BooleanField(default=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=30)),
                ('transactionType', models.CharField(blank=True, max_length=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Address')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OunceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gold22', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gold24', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('silver', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('passcode', models.IntegerField(default=-1)),
                ('panid', models.CharField(blank=True, max_length=20)),
                ('aadhaar', models.CharField(blank=True, max_length=20)),
                ('companyType', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('commission', models.FloatField()),
            ],
        ),
    ]
